# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.cache/wt [current_project]
set_property parent.project_path /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/imports/rtl/general/n_plus_k_div_ROM.coe
add_files /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/imports/rtl/general/n_plus_k_ROM.coe
add_files /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/imports/rtl/general/n_plus_k_div_ROM_k64.coe
add_files /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/imports/rtl/general/n_plus_k_ROM_k64.coe
read_verilog -library xil_defaultlib {
  /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/imports/rtl/AES_Comp.v
  /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/imports/rtl/uart/rxuartlite.v
  /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/imports/rtl/uart/txuartlite.v
}
read_vhdl -library xil_defaultlib {
  /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/imports/rtl/packages/design_package.vhd
  /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/imports/rtl/general/BRAM_dual_clock.vhd
  /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/imports/rtl/general/FSM_FIFO.vhd
  /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/imports/rtl/uart/UART.vhd
  /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/imports/rtl/io_controller/address_dec.vhd
  /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/imports/rtl/io_controller/config_registers.vhd
  /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/imports/rtl/general/counter_up.vhd
  /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/imports/rtl/io_controller/data_dec.vhd
  /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/imports/rtl/io_controller/data_enc.vhd
  /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/imports/rtl/io_controller/io_controller_fifo_aes.vhd
  /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/imports/rtl/io_controller/io_fsm_fifo_aes.vhd
  /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/imports/rtl/io_wrapper.vhd
  /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/imports/rtl/read_traces.vhd
  /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/imports/rtl/reset_wrapper.vhd
  /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/imports/rtl/sensor/sensor.vhd
  /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/imports/rtl/sensor/sensor_top.vhd
  /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/imports/rtl/sig_delay.vhd
  /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/imports/rtl/xadc.vhd
  /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/imports/rtl/system_top_artix7_fifo_aes.vhd
}
read_ip -quiet /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property used_in_implementation false [get_files -all /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_ooc.xdc]

read_ip -quiet /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/ip/reset_gen/reset_gen.xci
set_property used_in_implementation false [get_files -all /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/ip/reset_gen/reset_gen_board.xdc]
set_property used_in_implementation false [get_files -all /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/ip/reset_gen/reset_gen.xdc]
set_property used_in_implementation false [get_files -all /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/ip/reset_gen/reset_gen_ooc.xdc]

read_ip -quiet /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/ip/clock_generator/clock_generator.xci
set_property used_in_implementation false [get_files -all /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/ip/clock_generator/clock_generator_board.xdc]
set_property used_in_implementation false [get_files -all /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/ip/clock_generator/clock_generator.xdc]
set_property used_in_implementation false [get_files -all /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/sources_1/ip/clock_generator/clock_generator_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/constrs_1/imports/xdc/constraints_RDS.xdc
set_property used_in_implementation false [get_files /home/galrene/school/bakalarka/RDS/basys3/rene_test/rene_test.srcs/constrs_1/imports/xdc/constraints_RDS.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top system_top -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file system_top_utilization_synth.rpt -pb system_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
